//HintName: UnitTests.BasicPrimaryKey.g.cs
// <auto-generated />

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

using System;
using CompositeKey;

namespace UnitTests
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CompositeKey.SourceGeneration", "VERSION")]
    public partial record BasicPrimaryKey : IPrimaryKey<BasicPrimaryKey>
    {
        public override string ToString()
        {
            return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}#{ThirdPart}");
        }

        public string ToPartitionKeyString()
        {
            return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}#{ThirdPart}");
        }

        public string ToPartitionKeyString(int throughPartIndex, bool includeTrailingDelimiter = true)
        {
            return (throughPartIndex, includeTrailingDelimiter) switch
            {
                (0, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}"),
                (0, true) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#"),
                (1, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}"),
                (1, true) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}#"),
                (2, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}#{ThirdPart}"),
                _ => throw new InvalidOperationException("Invalid combination of throughPartIndex and includeTrailingDelimiter provided")
            };
        }

        public static BasicPrimaryKey Parse(string primaryKey)
        {
            ArgumentNullException.ThrowIfNull(primaryKey);
        
            return Parse((ReadOnlySpan<char>)primaryKey);
        }
        
        public static BasicPrimaryKey Parse(ReadOnlySpan<char> primaryKey)
        {
            if (primaryKey.Length < 40)
                throw new FormatException("Unrecognized format.");
            
            const int expectedPrimaryKeyParts = 3;
            Span<Range> primaryKeyPartRanges = stackalloc Range[expectedPrimaryKeyParts + 1];
            if (primaryKey.Split(primaryKeyPartRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPrimaryKeyParts)
                throw new FormatException("Unrecognized format.");
            
            if (primaryKey[primaryKeyPartRanges[0]].Length != 36 || !Guid.TryParseExact(primaryKey[primaryKeyPartRanges[0]], "d", out var firstPart))
                throw new FormatException("Unrecognized format.");
            
            if (primaryKey[primaryKeyPartRanges[1]].Length == 0)
                throw new FormatException("Unrecognized format.");
            
            string secondPart = primaryKey[primaryKeyPartRanges[1]].ToString();
            
            if (!int.TryParse(primaryKey[primaryKeyPartRanges[2]], out var thirdPart))
                throw new FormatException("Unrecognized format.");
            
            return new BasicPrimaryKey() { FirstPart = firstPart, SecondPart = secondPart, ThirdPart = thirdPart };
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? primaryKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey? result)
        {
            if (primaryKey is null)
            {
                result = null;
                return false;
            }
        
            return TryParse((ReadOnlySpan<char>)primaryKey, out result);
        }
        
        public static bool TryParse(ReadOnlySpan<char> primaryKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey? result)
        {
            result = null;
        
            if (primaryKey.Length < 40)
                return false;
            
            const int expectedPrimaryKeyParts = 3;
            Span<Range> primaryKeyPartRanges = stackalloc Range[expectedPrimaryKeyParts + 1];
            if (primaryKey.Split(primaryKeyPartRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPrimaryKeyParts)
                return false;
            
            if (primaryKey[primaryKeyPartRanges[0]].Length != 36 || !Guid.TryParseExact(primaryKey[primaryKeyPartRanges[0]], "d", out var firstPart))
                return false;
            
            if (primaryKey[primaryKeyPartRanges[1]].Length == 0)
                return false;
            
            string secondPart = primaryKey[primaryKeyPartRanges[1]].ToString();
            
            if (!int.TryParse(primaryKey[primaryKeyPartRanges[2]], out var thirdPart))
                return false;
            
            result = new BasicPrimaryKey() { FirstPart = firstPart, SecondPart = secondPart, ThirdPart = thirdPart };
            return true;
        }

        /// <inheritdoc cref="IFormattable.ToString(string?, IFormatProvider?)" />
        string IFormattable.ToString(string? format, IFormatProvider? formatProvider) => ToString();
        
        /// <inheritdoc cref="IParsable{BasicPrimaryKey}.Parse(string, IFormatProvider?)" />
        static BasicPrimaryKey IParsable<BasicPrimaryKey>.Parse(string s, IFormatProvider? provider) => Parse(s);
        
        /// <inheritdoc cref="IParsable{BasicPrimaryKey}.TryParse(string?, IFormatProvider?, out BasicPrimaryKey)" />
        static bool IParsable<BasicPrimaryKey>.TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey result) => TryParse(s, out result);
        
        /// <inheritdoc cref="ISpanParsable{BasicPrimaryKey}.Parse(ReadOnlySpan{char}, IFormatProvider?)" />
        static BasicPrimaryKey ISpanParsable<BasicPrimaryKey>.Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => Parse(s);
        
        /// <inheritdoc cref="ISpanParsable{BasicPrimaryKey}.TryParse(ReadOnlySpan{char}, IFormatProvider?, out BasicPrimaryKey)" />
        static bool ISpanParsable<BasicPrimaryKey>.TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey result) => TryParse(s, out result);
    }
}
