//HintName: UnitTests.UserTagKey.g.cs
// <auto-generated />

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

using System;
using CompositeKey;

namespace UnitTests
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CompositeKey.SourceGeneration", "VERSION")]
    public partial record UserTagKey : ICompositePrimaryKey<UserTagKey>
    {
        public override string ToString()
        {
            if (Tags.Count == 0)
                throw new FormatException("Collection must contain at least one item.");
            
            var handler = new System.Runtime.CompilerServices.DefaultInterpolatedStringHandler(5, 1, global::System.Globalization.CultureInfo.InvariantCulture);
            handler.AppendFormatted(UserId, "d");
            handler.AppendLiteral("|");
            handler.AppendLiteral("TAG");
            handler.AppendLiteral("_");
            for (int i = 0; i < Tags.Count; i++)
            {
                if (i > 0)
                    handler.AppendLiteral("#");
                
                handler.AppendFormatted(Tags[i]);
            }

            return handler.ToStringAndClear();
        }

        public string ToPartitionKeyString()
        {
            return string.Create(36, this, static (destination, state) =>
            {
                int position = 0;

                {
                    if (!((ISpanFormattable)state.UserId).TryFormat(destination[position..], out int userIdCharsWritten, "d", global::System.Globalization.CultureInfo.InvariantCulture))
                    	throw new FormatException();

                    position += userIdCharsWritten;
                }
            });
        }

        public string ToPartitionKeyString(int throughPartIndex, bool includeTrailingDelimiter = true)
        {
            return (throughPartIndex, includeTrailingDelimiter) switch
            {
                (0, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{UserId:d}"),
                _ => throw new InvalidOperationException("Invalid combination of throughPartIndex and includeTrailingDelimiter provided")
            };
        }

        public string ToSortKeyString()
        {
            if (Tags.Count == 0)
                throw new FormatException("Collection must contain at least one item.");
            
            var handler = new System.Runtime.CompilerServices.DefaultInterpolatedStringHandler(4, 0, global::System.Globalization.CultureInfo.InvariantCulture);
            handler.AppendLiteral("TAG");
            handler.AppendLiteral("_");
            for (int i = 0; i < Tags.Count; i++)
            {
                if (i > 0)
                    handler.AppendLiteral("#");
                
                handler.AppendFormatted(Tags[i]);
            }

            return handler.ToStringAndClear();
        }

        public string ToSortKeyString(int throughPartIndex, bool includeTrailingDelimiter = true)
        {
            switch (throughPartIndex, includeTrailingDelimiter)
            {
                case (0, false): return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"TAG");
                case (0, true): return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"TAG_");
            }

            int fixedPartCount = 1;
            int repeatIndex = throughPartIndex - fixedPartCount;
            int repeatCount = Math.Min(repeatIndex + 1, Tags.Count);
            if (repeatCount <= 0)
                throw new InvalidOperationException("Invalid throughPartIndex for repeating section.");
            
            var handler = new System.Runtime.CompilerServices.DefaultInterpolatedStringHandler(0, 0, global::System.Globalization.CultureInfo.InvariantCulture);
            handler.AppendFormatted(string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"TAG_"));

            for (int i = 0; i < repeatCount; i++)
            {
                if (i > 0)
                {
                    handler.AppendLiteral("#");
                }

                handler.AppendFormatted(Tags[i]);
            }

            if (includeTrailingDelimiter)
            {
                handler.AppendLiteral("#");
            }

            return handler.ToStringAndClear();
        }

        public static UserTagKey Parse(string primaryKey)
        {
            ArgumentNullException.ThrowIfNull(primaryKey);
        
            return Parse((ReadOnlySpan<char>)primaryKey);
        }
        
        public static UserTagKey Parse(ReadOnlySpan<char> primaryKey)
        {
            const int expectedPrimaryKeyParts = 2;
            Span<Range> primaryKeyPartRanges = stackalloc Range[expectedPrimaryKeyParts + 1];
            if (primaryKey.Split(primaryKeyPartRanges, '|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPrimaryKeyParts)
                throw new FormatException("Unrecognized format.");
            
            return Parse(primaryKey[primaryKeyPartRanges[0]], primaryKey[primaryKeyPartRanges[1]]);
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? primaryKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out UserTagKey? result)
        {
            if (primaryKey is null)
            {
                result = null;
                return false;
            }
        
            return TryParse((ReadOnlySpan<char>)primaryKey, out result);
        }
        
        public static bool TryParse(ReadOnlySpan<char> primaryKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out UserTagKey? result)
        {
            result = null;
        
            const int expectedPrimaryKeyParts = 2;
            Span<Range> primaryKeyPartRanges = stackalloc Range[expectedPrimaryKeyParts + 1];
            if (primaryKey.Split(primaryKeyPartRanges, '|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPrimaryKeyParts)
                return false;
            
            return TryParse(primaryKey[primaryKeyPartRanges[0]], primaryKey[primaryKeyPartRanges[1]], out result);
        }

        public static UserTagKey Parse(string partitionKey, string sortKey)
        {
            ArgumentNullException.ThrowIfNull(partitionKey);
            ArgumentNullException.ThrowIfNull(sortKey);
        
            return Parse((ReadOnlySpan<char>)partitionKey, (ReadOnlySpan<char>)sortKey);
        }
        
        public static UserTagKey Parse(ReadOnlySpan<char> partitionKey, ReadOnlySpan<char> sortKey)
        {
            if (partitionKey.Length != 36)
                throw new FormatException("Unrecognized format.");
            
            if (sortKey.Length < 5)
                throw new FormatException("Unrecognized format.");
            
            const int expectedSortKeyParts = 2;
            Span<Range> sortKeyPartRanges = stackalloc Range[expectedSortKeyParts + 1];
            if (sortKey.Split(sortKeyPartRanges, '_', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedSortKeyParts)
                throw new FormatException("Unrecognized format.");
            
            if (partitionKey.Length != 36 || !Guid.TryParseExact(partitionKey, "d", out var userId))
                throw new FormatException("Unrecognized format.");
            
            if (!sortKey[sortKeyPartRanges[0]].Equals("TAG", StringComparison.Ordinal))
                throw new FormatException("Unrecognized format.");
            
            Span<Range> tagsRanges = stackalloc Range[128];
            int tagsCount = sortKey[sortKeyPartRanges[1]].Split(tagsRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (tagsCount < 1)
                throw new FormatException("Unrecognized format.");
            
            var tags = new global::System.Collections.Generic.List<string>();
            for (int ri = 0; ri < tagsCount; ri++)
            {
                if (sortKey[sortKeyPartRanges[1]][tagsRanges[ri]].Length == 0)
                    throw new FormatException("Unrecognized format.");
                tags.Add(sortKey[sortKeyPartRanges[1]][tagsRanges[ri]].ToString());
            }

            if (tags.Count == 0)
                throw new FormatException("Unrecognized format.");
            
            return new UserTagKey() { UserId = userId, Tags = tags };
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string partitionKey, string sortKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out UserTagKey? result)
        {
            if (partitionKey is null || sortKey is null)
            {
                result = null;
                return false;
            }
        
            return TryParse((ReadOnlySpan<char>)partitionKey, (ReadOnlySpan<char>)sortKey, out result);
        }
        
        public static bool TryParse(ReadOnlySpan<char> partitionKey, ReadOnlySpan<char> sortKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out UserTagKey? result)
        {
            result = null;
        
            if (partitionKey.Length != 36)
                return false;
            
            if (sortKey.Length < 5)
                return false;
            
            const int expectedSortKeyParts = 2;
            Span<Range> sortKeyPartRanges = stackalloc Range[expectedSortKeyParts + 1];
            if (sortKey.Split(sortKeyPartRanges, '_', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedSortKeyParts)
                return false;
            
            if (partitionKey.Length != 36 || !Guid.TryParseExact(partitionKey, "d", out var userId))
                return false;
            
            if (!sortKey[sortKeyPartRanges[0]].Equals("TAG", StringComparison.Ordinal))
                return false;
            
            Span<Range> tagsRanges = stackalloc Range[128];
            int tagsCount = sortKey[sortKeyPartRanges[1]].Split(tagsRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            if (tagsCount < 1)
                return false;
            
            var tags = new global::System.Collections.Generic.List<string>();
            for (int ri = 0; ri < tagsCount; ri++)
            {
                if (sortKey[sortKeyPartRanges[1]][tagsRanges[ri]].Length == 0)
                    return false;
                tags.Add(sortKey[sortKeyPartRanges[1]][tagsRanges[ri]].ToString());
            }

            if (tags.Count == 0)
                return false;
            
            result = new UserTagKey() { UserId = userId, Tags = tags };
            return true;
        }

        /// <inheritdoc cref="IFormattable.ToString(string?, IFormatProvider?)" />
        string IFormattable.ToString(string? format, IFormatProvider? formatProvider) => ToString();
        
        /// <inheritdoc cref="IParsable{UserTagKey}.Parse(string, IFormatProvider?)" />
        static UserTagKey IParsable<UserTagKey>.Parse(string s, IFormatProvider? provider) => Parse(s);
        
        /// <inheritdoc cref="IParsable{UserTagKey}.TryParse(string?, IFormatProvider?, out UserTagKey)" />
        static bool IParsable<UserTagKey>.TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out UserTagKey result) => TryParse(s, out result);
        
        /// <inheritdoc cref="ISpanParsable{UserTagKey}.Parse(ReadOnlySpan{char}, IFormatProvider?)" />
        static UserTagKey ISpanParsable<UserTagKey>.Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => Parse(s);
        
        /// <inheritdoc cref="ISpanParsable{UserTagKey}.TryParse(ReadOnlySpan{char}, IFormatProvider?, out UserTagKey)" />
        static bool ISpanParsable<UserTagKey>.TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out UserTagKey result) => TryParse(s, out result);
    }
}
