//HintName: AnotherNamespace.BasicPrimaryKey.g.cs
// <auto-generated />

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

using System;
using CompositeKey;

namespace AnotherNamespace
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("CompositeKey.SourceGeneration", "VERSION")]
    public partial record BasicPrimaryKey : ICompositePrimaryKey<BasicPrimaryKey>
    {
        public override string ToString()
        {
            return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}|ConstantValue#{ThirdPart:x}");
        }

        public string ToPartitionKeyString()
        {
            return string.Create(37 + SecondPart.Length, this, static (destination, state) =>
            {
                int position = 0;

                {
                    if (!((ISpanFormattable)state.FirstPart).TryFormat(destination[position..], out int firstPartCharsWritten, "d", global::System.Globalization.CultureInfo.InvariantCulture))
                    	throw new FormatException();

                    position += firstPartCharsWritten;
                }

                destination[position] = '#';
                position += 1;

                state.SecondPart.CopyTo(destination[position..]);
                position += state.SecondPart.Length;
            });
        }

        public string ToPartitionKeyString(int throughPartIndex, bool includeTrailingDelimiter = true)
        {
            return (throughPartIndex, includeTrailingDelimiter) switch
            {
                (0, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}"),
                (0, true) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#"),
                (1, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"{FirstPart:d}#{SecondPart}"),
                _ => throw new InvalidOperationException("Invalid combination of throughPartIndex and includeTrailingDelimiter provided")
            };
        }

        public string ToSortKeyString()
        {
            return string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"ConstantValue#{ThirdPart:x}");
        }

        public string ToSortKeyString(int throughPartIndex, bool includeTrailingDelimiter = true)
        {
            return (throughPartIndex, includeTrailingDelimiter) switch
            {
                (0, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"ConstantValue"),
                (0, true) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"ConstantValue#"),
                (1, false) => string.Create(global::System.Globalization.CultureInfo.InvariantCulture, $"ConstantValue#{ThirdPart:x}"),
                _ => throw new InvalidOperationException("Invalid combination of throughPartIndex and includeTrailingDelimiter provided")
            };
        }

        public static BasicPrimaryKey Parse(string primaryKey)
        {
            ArgumentNullException.ThrowIfNull(primaryKey);
        
            return Parse((ReadOnlySpan<char>)primaryKey);
        }
        
        public static BasicPrimaryKey Parse(ReadOnlySpan<char> primaryKey)
        {
            const int expectedPrimaryKeyParts = 2;
            Span<Range> primaryKeyPartRanges = stackalloc Range[expectedPrimaryKeyParts + 1];
            if (primaryKey.Split(primaryKeyPartRanges, '|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPrimaryKeyParts)
                throw new FormatException("Unrecognized format.");
            
            return Parse(primaryKey[primaryKeyPartRanges[0]], primaryKey[primaryKeyPartRanges[1]]);
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? primaryKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey? result)
        {
            if (primaryKey is null)
            {
                result = null;
                return false;
            }
        
            return TryParse((ReadOnlySpan<char>)primaryKey, out result);
        }
        
        public static bool TryParse(ReadOnlySpan<char> primaryKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey? result)
        {
            result = null;
        
            const int expectedPrimaryKeyParts = 2;
            Span<Range> primaryKeyPartRanges = stackalloc Range[expectedPrimaryKeyParts + 1];
            if (primaryKey.Split(primaryKeyPartRanges, '|', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPrimaryKeyParts)
                return false;
            
            return TryParse(primaryKey[primaryKeyPartRanges[0]], primaryKey[primaryKeyPartRanges[1]], out result);
        }

        public static BasicPrimaryKey Parse(string partitionKey, string sortKey)
        {
            ArgumentNullException.ThrowIfNull(partitionKey);
            ArgumentNullException.ThrowIfNull(sortKey);
        
            return Parse((ReadOnlySpan<char>)partitionKey, (ReadOnlySpan<char>)sortKey);
        }
        
        public static BasicPrimaryKey Parse(ReadOnlySpan<char> partitionKey, ReadOnlySpan<char> sortKey)
        {
            if (partitionKey.Length < 38)
                throw new FormatException("Unrecognized format.");
            
            if (sortKey.Length < 46)
                throw new FormatException("Unrecognized format.");
            
            const int expectedPartitionKeyParts = 2;
            Span<Range> partitionKeyPartRanges = stackalloc Range[expectedPartitionKeyParts + 1];
            if (partitionKey.Split(partitionKeyPartRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPartitionKeyParts)
                throw new FormatException("Unrecognized format.");
            
            const int expectedSortKeyParts = 2;
            Span<Range> sortKeyPartRanges = stackalloc Range[expectedSortKeyParts + 1];
            if (sortKey.Split(sortKeyPartRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedSortKeyParts)
                throw new FormatException("Unrecognized format.");
            
            if (partitionKey[partitionKeyPartRanges[0]].Length != 36 || !Guid.TryParseExact(partitionKey[partitionKeyPartRanges[0]], "d", out var firstPart))
                throw new FormatException("Unrecognized format.");
            
            if (partitionKey[partitionKeyPartRanges[1]].Length == 0)
                throw new FormatException("Unrecognized format.");
            
            string secondPart = partitionKey[partitionKeyPartRanges[1]].ToString();
            
            if (!sortKey[sortKeyPartRanges[0]].Equals("ConstantValue", StringComparison.Ordinal))
                throw new FormatException("Unrecognized format.");
            
            if (!Guid.TryParseExact(sortKey[sortKeyPartRanges[1]], "x", out var thirdPart))
                throw new FormatException("Unrecognized format.");
            
            return new BasicPrimaryKey(firstPart, secondPart, thirdPart);
        }

        public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string partitionKey, string sortKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey? result)
        {
            if (partitionKey is null || sortKey is null)
            {
                result = null;
                return false;
            }
        
            return TryParse((ReadOnlySpan<char>)partitionKey, (ReadOnlySpan<char>)sortKey, out result);
        }
        
        public static bool TryParse(ReadOnlySpan<char> partitionKey, ReadOnlySpan<char> sortKey, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey? result)
        {
            result = null;
        
            if (partitionKey.Length < 38)
                return false;
            
            if (sortKey.Length < 46)
                return false;
            
            const int expectedPartitionKeyParts = 2;
            Span<Range> partitionKeyPartRanges = stackalloc Range[expectedPartitionKeyParts + 1];
            if (partitionKey.Split(partitionKeyPartRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedPartitionKeyParts)
                return false;
            
            const int expectedSortKeyParts = 2;
            Span<Range> sortKeyPartRanges = stackalloc Range[expectedSortKeyParts + 1];
            if (sortKey.Split(sortKeyPartRanges, '#', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries) != expectedSortKeyParts)
                return false;
            
            if (partitionKey[partitionKeyPartRanges[0]].Length != 36 || !Guid.TryParseExact(partitionKey[partitionKeyPartRanges[0]], "d", out var firstPart))
                return false;
            
            if (partitionKey[partitionKeyPartRanges[1]].Length == 0)
                return false;
            
            string secondPart = partitionKey[partitionKeyPartRanges[1]].ToString();
            
            if (!sortKey[sortKeyPartRanges[0]].Equals("ConstantValue", StringComparison.Ordinal))
                return false;
            
            if (!Guid.TryParseExact(sortKey[sortKeyPartRanges[1]], "x", out var thirdPart))
                return false;
            
            result = new BasicPrimaryKey(firstPart, secondPart, thirdPart);
            return true;
        }

        /// <inheritdoc cref="IFormattable.ToString(string?, IFormatProvider?)" />
        string IFormattable.ToString(string? format, IFormatProvider? formatProvider) => ToString();
        
        /// <inheritdoc cref="IParsable{BasicPrimaryKey}.Parse(string, IFormatProvider?)" />
        static BasicPrimaryKey IParsable<BasicPrimaryKey>.Parse(string s, IFormatProvider? provider) => Parse(s);
        
        /// <inheritdoc cref="IParsable{BasicPrimaryKey}.TryParse(string?, IFormatProvider?, out BasicPrimaryKey)" />
        static bool IParsable<BasicPrimaryKey>.TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey result) => TryParse(s, out result);
        
        /// <inheritdoc cref="ISpanParsable{BasicPrimaryKey}.Parse(ReadOnlySpan{char}, IFormatProvider?)" />
        static BasicPrimaryKey ISpanParsable<BasicPrimaryKey>.Parse(ReadOnlySpan<char> s, IFormatProvider? provider) => Parse(s);
        
        /// <inheritdoc cref="ISpanParsable{BasicPrimaryKey}.TryParse(ReadOnlySpan{char}, IFormatProvider?, out BasicPrimaryKey)" />
        static bool ISpanParsable<BasicPrimaryKey>.TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, [global::System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out BasicPrimaryKey result) => TryParse(s, out result);
    }
}
